export interface Evaluacion {
  nombre: String;
  apellido: String;
  sexo: String;
  cedula: String;
  nss: String;
  regimen: String;
  telefono: String;
  tipo_de_contacto: String;
  nombre_contacto: String;
  especificacion_contacto: String;
  unap: String;
  region: String;
  provincia: String;
  municipio: String;
  estado: String;
  talla: Number;
  peso: Number;
  cintura: Number;
  abdomen: Number;
  cadera: Number;
  altura_rodilla: Number;
  "Cintura/Cadera": String;
  presion_arterial_sistolica: Number;
  presion_arterial_diatolica: Number;
  frecuencia_cardiaca: Number;
  fuerza: Number;
  imc: String;
  flexibilidad_miembro_superior: String;
  flexibilidad_miembro_inferior: String;
  pliegue_bicep: Number;
  pliegue_abdominal: Number;
  pliegue_sub: Number;
  Encamado: String;
  Edentulo: String;
  "vive solo": String;
  abandono: String;
  maltrato: String;
  "exceso medicamento": Boolean;
  specialist_appo_psiqui: Boolean;
  specialist_appo_geria: Boolean;
  specialist_appo_orto: Boolean;
  specialist_appo_gastro: Boolean;
  specialist_appo_oftal: Boolean;
  specialist_appo_psicolo: Boolean;
  specialist_appo_neurolo: Boolean;
  specialist_appo_fisia: Boolean;
  specialist_appo_cardio: Boolean;
  specialist_appo_odonto: Boolean;
  specialist_appo_urolo: Boolean;
  specialist_appo_diabe: Boolean;
  "Andador 4 Ruedas": Boolean;
  "Andador 4 Patas": Boolean;
  Bastón: Boolean;
  "Bastón 4 P": Boolean;
  "Bastón No VIdente": Boolean;
  "Cama de Posición": Boolean;
  "Colchón Aire": Boolean;
  "Faja Obdominal": Boolean;
  Glucómetro: Boolean;
  "Inodoro Porta": Boolean;
  Muletas: Boolean;
  "Pampers XL": Boolean;
  "Pampers L": Boolean;
  "Pampers M": Boolean;
  "Pampers S": Boolean;
  "Silla de Baño": Boolean;
  "Media de Comprensión": Boolean;
  fecha: Number;
  fechaAuts: Number;
  kit: String;
  nombre_doctor: String;
  comentary: String;
  comentaryNutri: String;
  eval_nutri_1: String;
  eval_nutri_2: String;
  eval_nutri_3: String;
  eval_nutri_4: String;
  eval_nutri_5: String;
  eval_nutri_6: String;
  eval_nutri_7: String;
  eval_nutri_8: String;
  eval_nutri_9: String;
  eval_nutri_10: String;
  fechaNacimiento: Date;
  edad: Number;
  direccion: String;
  status: String;
  id_center: String;
  id_patient: String;
  id_form: String;
  id_doctor: String;
  precio: Number;
  supervisor: String;
  autorizPor: String;
  autorizacion: String;
  pctoGrasa: String;
  estadoImc: String;
  estadoFuerza: String;
  riesgoCardiovascular: String;
  statusAdministrativo: String;
  estadofc: String;
  cambioKit: Boolean;
  consAfil: Boolean;
  evaluacion: Boolean;
  verificacion: Boolean;
  autorizado: Boolean;
  evaluado: Boolean;
  justificacionCambioKit: String;
  riesgoNutricional: String;
  order: Number;
  
  datPersCorrc: Boolean;
  todCompc: Boolean;
  pacRefe: Boolean;
  asiCiónCorc: Boolean;
  comsPert: Boolean;
  escSirsCorr: Boolean;
  escEvCoc: Boolean;
  todFirmCompc: Boolean;
  todCorrc: Boolean;
  sinTachadEnm: Boolean;
  
  cantidadEvaluaciones: Number;
}
